name: build_website

on:

  push:
    branches:
      - master
      - main

  # this ensures that the website is built when a PR is opened, synchronized, reopened, or closed
  # and the PR is not breaking the website building process
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master

permissions:
  contents: write
  deployments: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pypandoc_binary
        pip install .[doc]

    - name: Setup pandoc
      uses: siacodelabs/setup-pandoc@v1
      with:
        xelatex: true

    - name: Build documentation
      run: |
        sphinx-apidoc -o website/_autosummary atomdb -M -f

    - name: Create soft links
      run: |
        cd website
        cp -lR ../docs/notebooks ./examples
        ln -s ../docs/source ./api
        cd ../

    - name: Install Requirements
      run: |
        python3 -m pip install -r website/requirements.txt

    - name: Build Jupyter Book
      run: |
        jupyter-book build ./website/

      # Push the book's HTML to github-pages
      # inspired by https://github.com/orgs/community/discussions/26724
      # only push to gh-pages if the master branch has been updated
    - name: GitHub Pages Action
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/_build/html
        publish_branch: gh-pages
        cname: atomdb.qcdevs.org
